export const products = [
  {
    id: 0,
    title: "Сказочное заморское яство",
    titleActiveHover: "Котэ не одобряет?",
    name: "Нямушка",
    consist: "с фуа-гра",
    count: 10,
    bonuses: ["мышь в подарок"],
    weight: "0,5",
    status: "notSelected",
    labelText: "Печень утки разварная с артишоками.",
  },
  {
    id: 1,
    title: "Сказочное заморское яство",
    titleActiveHover: "Котэ не одобряет?",
    name: "Нямушка",
    consist: "с рыбой",
    count: 40,
    bonuses: ["2 мыши в подарок"],
    weight: "2",
    status: "selected",
    labelText: "Головы щучьи с чесноком да свежайшая сёмгушка.",
  },
  {
    id: 2,
    title: "Сказочное заморское яство",
    titleActiveHover: "Котэ не одобряет?",
    name: "Нямушка",
    consist: "с курой",
    count: 100,
    bonuses: ["5 мышей в подарок", "заказчик доволен"],
    weight: "5",
    status: "disabled",
    labelText: "Филе из цыплят с трюфелями в бульоне.",
  },
];
